#!/usr/bin/env bash
# Interactive env.local writer. Sourced by install-macos.sh and install-linux.sh.
#
# Philosophy: env.local should only contain keys the user actually wants to set
# (secrets + per-machine paths). Anything left at its default is omitted, so the
# file stays short and the C# defaults in BotConfig.cs remain the single source
# of truth. Want to override a default later? Add the key by hand — see
# env.local.example for the full list.
set -euo pipefail

ENV_FILE="${ENV_FILE:?ENV_FILE must be set}"
EXAMPLE_FILE="${EXAMPLE_FILE:?EXAMPLE_FILE must be set}"
NON_INTERACTIVE="${NON_INTERACTIVE:-0}"
FORCE="${FORCE:-0}"

if [[ -f "$ENV_FILE" && "$FORCE" != "1" ]]; then
    echo "env.local already exists at $ENV_FILE — skipping wizard (re-run with --force to regenerate)."
    return 0 2>/dev/null || exit 0
fi

: "${DEFAULT_JAVA_HOME:=}"
: "${DEFAULT_ANDROID_SDK_ROOT:=}"

ask() {
    local prompt="$1"; local default="$2"; local answer
    if [[ "$NON_INTERACTIVE" == "1" ]]; then echo "$default"; return; fi
    if [[ -n "$default" ]]; then
        read -r -p "  $prompt [$default]: " answer </dev/tty || true
    else
        read -r -p "  $prompt: " answer </dev/tty || true
    fi
    echo "${answer:-$default}"
}

ask_secret() {
    local prompt="$1"; local default="$2"; local answer
    if [[ "$NON_INTERACTIVE" == "1" ]]; then echo "$default"; return; fi
    read -r -s -p "  $prompt: " answer </dev/tty || true
    echo "" 1>&2
    echo "${answer:-$default}"
}

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  env.local wizard — only required keys are prompted."
echo "  Everything else uses defaults from BotConfig.cs."
echo "  See $EXAMPLE_FILE for the full list of optional keys."
echo "════════════════════════════════════════════════════════════"
echo ""

echo "▶ Telegram (required)"
TG_TOKEN="$(ask_secret 'TELEGRAM_BOT_TOKEN (from @BotFather)' '')"
TG_API_ID="$(ask 'TELEGRAM_API_ID (from my.telegram.org)' '')"
TG_API_HASH="$(ask_secret 'TELEGRAM_API_HASH (from my.telegram.org)' '')"

echo ""
echo "▶ Repository (required)"
REPO_PATH_DEFAULT="${REPO_PATH_OVERRIDE:-$HOME/Desktop/AirCaseProject/mobile_aplication}"
REPO_PATH_VAL="$(ask 'REPO_PATH (absolute path to existing Flutter project)' "$REPO_PATH_DEFAULT")"
REPO_BRANCH_VAL="$(ask 'REPO_BRANCH' "${REPO_BRANCH_OVERRIDE:-master}")"

echo ""
echo "▶ Android toolchain (recommended — leave blank to rely on PATH)"
JAVA_HOME_VAL="$(ask 'JAVA_HOME' "$DEFAULT_JAVA_HOME")"
ANDROID_SDK_VAL="$(ask 'ANDROID_SDK_ROOT' "$DEFAULT_ANDROID_SDK_ROOT")"

echo ""
echo "▶ Optional — set up SSH for private repo (leave blank to skip)"
REPO_SSH_KEY="$(ask 'REPO_SSH_KEY_PATH' '')"

mkdir -p "$(dirname "$ENV_FILE")"
{
    echo "# Generated by install script on $(date '+%Y-%m-%dT%H:%M:%S%z')"
    echo "# Only required + user-set keys are written here. Defaults live in BotConfig.cs."
    echo "# See $EXAMPLE_FILE for every optional key you can add."
    echo ""
    echo "# --- Required ---"
    echo "TELEGRAM_BOT_TOKEN=$TG_TOKEN"
    echo "TELEGRAM_API_ID=$TG_API_ID"
    echo "TELEGRAM_API_HASH=$TG_API_HASH"
    echo "REPO_PATH=$REPO_PATH_VAL"
    echo "REPO_BRANCH=$REPO_BRANCH_VAL"

    # Only emit the optional keys the user actually set.
    if [[ -n "$JAVA_HOME_VAL" || -n "$ANDROID_SDK_VAL" || -n "$REPO_SSH_KEY" ]]; then
        echo ""
        echo "# --- Optional overrides ---"
    fi
    [[ -n "$JAVA_HOME_VAL"    ]] && echo "JAVA_HOME=$JAVA_HOME_VAL"
    [[ -n "$ANDROID_SDK_VAL"  ]] && echo "ANDROID_SDK_ROOT=$ANDROID_SDK_VAL"
    [[ -n "$REPO_SSH_KEY"     ]] && echo "REPO_SSH_KEY_PATH=$REPO_SSH_KEY"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo ""
echo "✅ Wrote $ENV_FILE (chmod 600)"
echo "   To override more knobs (heartbeat, queue size, flavor, etc.), copy lines"
echo "   from $EXAMPLE_FILE into $ENV_FILE."
